PhysicalPropertyParams = {
    "rs": ['P', 15],
    "r": ['Q', 16],
    "rd": ['R', 17],
    "n": ['S', 18],
    "e": ['T', 19],
    "W": ['U', 20],
    "Sr": ['V', 21],
    "Wl": ['W', 22],
    "Wp": ['X', 23],
    "Ip": ['Y', 24],
    "Il": ['Z', 25],
    "Ir": ['AE', 30],
    "Kf_min": ['AA', 26],
    "Kf_max": ['AB', 27],
    "rd_min": ['AC', 28],
    "rd_max": ['AD', 29],
    "slope_angle_dry": ['AF', 31],
    "slope_angle_wet": ['AG', 32],
    "granulometric_10": ['E', 4],
    "granulometric_5": ['F', 5],
    "granulometric_2": ['G', 6],
    "granulometric_1": ['H', 7],
    "granulometric_05": ['I', 8],
    "granulometric_025": ['J', 9],
    "granulometric_01": ['K', 10],
    "granulometric_005": ['L', 11],
    "granulometric_001": ['M', 12],
    "granulometric_0002": ['N', 13],
    "granulometric_0000": ['O', 14],
}

GroundTypes = {
    1: "Песок гравелистый",
    2: "Песок крупный",
    3: "Песок средней крупности",
    4: "Песок мелкий",
    5: "Песок пылеватый",
    6: "Супесь",
    7: "Суглинок",
    8: "Глина",
    9: "Торф",
}
